"""add active and deadline to jobs

Revision ID: 467d9cabb339
Revises: 8fda79b4bad2
Create Date: 2026-05-09 11:30:27.290411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '467d9cabb339'
down_revision: Union[str, Sequence[str], None] = '8fda79b4bad2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('membership_counters')
    op.add_column(
        'jobs',
        sa.Column('is_active', sa.Boolean(), nullable=True)
    )

    op.execute(
        """
        ALTER TABLE jobs
        ALTER COLUMN application_deadline
        TYPE DATE
        USING application_deadline::date
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'application_deadline',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('jobs', 'is_active')
    op.create_table('membership_counters',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('current_value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('membership_counters_pkey')),
    sa.UniqueConstraint('type', name=op.f('membership_counters_type_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
