"""added updated and deleted columns to job table

Revision ID: 5d5ef501cfcf
Revises: fbe961ee4df4
Create Date: 2026-05-11 13:03:26.124123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d5ef501cfcf'
down_revision: Union[str, Sequence[str], None] = 'fbe961ee4df4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('membership_counters')
    op.add_column('jobs', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('jobs', sa.Column('deleted_by', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'deleted_at')
    op.drop_column('jobs', 'deleted_by')
    op.drop_column('jobs', 'updated_at')
    op.drop_column('jobs', 'updated_by')
    op.create_table('membership_counters',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('current_value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('membership_counters_pkey')),
    sa.UniqueConstraint('type', name=op.f('membership_counters_type_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
