"""approved_at rejected_at columns added to member model 

Revision ID: 86b967237bdc
Revises: 78e352e6fb3a
Create Date: 2026-05-04 16:03:31.101441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86b967237bdc'
down_revision: Union[str, Sequence[str], None] = '78e352e6fb3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('members', sa.Column('approved_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('members', sa.Column('rejected_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'rejected_at')
    op.drop_column('members', 'approved_at')
    op.drop_column('members', 'status')
    # ### end Alembic commands ###
