"""update jobs table

Revision ID: 8fda79b4bad2
Revises: c18da327c840
Create Date: 2026-05-08 13:11:41.573401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fda79b4bad2'
down_revision: Union[str, Sequence[str], None] = 'c18da327c840'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('membership_counters')
    op.add_column('jobs', sa.Column('title', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('qualification', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('experience_min', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('experience_max', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('salary_min', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('salary_max', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('perks', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('location', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('locality', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('created_by_role', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('rejected_at', sa.DateTime(), nullable=True))
    op.alter_column('jobs', 'application_deadline',
               existing_type=sa.DATE(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('jobs_posted_by_fkey'), 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'posted_by')
    op.drop_column('jobs', 'min_experience')
    op.drop_column('jobs', 'approved_by')
    op.drop_column('jobs', 'max_salary')
    op.drop_column('jobs', 'job_locality')
    op.drop_column('jobs', 'min_salary')
    op.drop_column('jobs', 'membership_id')
    op.drop_column('jobs', 'max_experience')
    op.drop_column('jobs', 'perks_benefits')
    op.drop_column('jobs', 'posted_by_type')
    op.drop_column('jobs', 'job_location')
    op.drop_column('jobs', 'qualification_required')
    op.drop_column('jobs', 'roles_responsibilities')
    op.drop_column('jobs', 'job_title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('job_title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('roles_responsibilities', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('qualification_required', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('job_location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('posted_by_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('perks_benefits', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('max_experience', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('membership_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('min_salary', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('job_locality', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('max_salary', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('approved_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('min_experience', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('posted_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('jobs_posted_by_fkey'), 'jobs', 'members', ['posted_by'], ['id'])
    op.alter_column('jobs', 'application_deadline',
               existing_type=sa.String(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.drop_column('jobs', 'rejected_at')
    op.drop_column('jobs', 'created_by_role')
    op.drop_column('jobs', 'created_by')
    op.drop_column('jobs', 'locality')
    op.drop_column('jobs', 'location')
    op.drop_column('jobs', 'perks')
    op.drop_column('jobs', 'salary_max')
    op.drop_column('jobs', 'salary_min')
    op.drop_column('jobs', 'experience_max')
    op.drop_column('jobs', 'experience_min')
    op.drop_column('jobs', 'qualification')
    op.drop_column('jobs', 'description')
    op.drop_column('jobs', 'title')
    op.create_table('membership_counters',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('current_value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('membership_counters_pkey')),
    sa.UniqueConstraint('type', name=op.f('membership_counters_type_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
