"""add otp_verifications table

Revision ID: a6f9bcf19941
Revises: ed37eb86e544
Create Date: 2026-04-17 19:20:56.471822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6f9bcf19941'
down_revision: Union[str, Sequence[str], None] = 'ed37eb86e544'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('representative_autonomous_details')
    op.drop_table('representative_both_details')
    op.drop_table('representative_university_details')
    op.drop_table('membership_counters')
    op.add_column('otp_verifications', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('otp_verifications', 'created_at')
    op.create_table('membership_counters',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('current_value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('membership_counters_pkey')),
    sa.UniqueConstraint('type', name=op.f('membership_counters_type_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('representative_university_details',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('college_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('university_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('college_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('designation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('district', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pincode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('representative_university_details_member_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('representative_university_details_pkey'))
    )
    op.create_table('representative_both_details',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('college_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('university_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('college_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('designation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('district', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pincode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('university_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('experience', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('official_mail_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mobile_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('representative_both_details_member_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('representative_both_details_pkey'))
    )
    op.create_table('representative_autonomous_details',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('college_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('college_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('designation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('district', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pincode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('representative_autonomous_details_member_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('representative_autonomous_details_pkey'))
    )
    # ### end Alembic commands ###
