"""add otp flags and student updates

Revision ID: ed37eb86e544
Revises: b1f90eedb01b
Create Date: 2026-04-17 18:16:43.536040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed37eb86e544'
down_revision: Union[str, Sequence[str], None] = 'b1f90eedb01b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('representative_university_details')
    op.drop_table('representative_autonomous_details')
    op.drop_table('membership_counters')
    op.drop_table('representative_both_details')
    op.alter_column('members', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('members', 'dob',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('members', 'state',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('members', 'district',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('members', 'pincode',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('members', 'mobile',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('members', 'candidate_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('members', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('otp_verifications', sa.Column('is_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('otp_verifications', 'is_verified')
    op.alter_column('members', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('members', 'candidate_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('members', 'mobile',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('members', 'pincode',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('members', 'district',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('members', 'state',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('members', 'dob',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('members', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_table('representative_both_details',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('college_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('university_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('college_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('designation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('district', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pincode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('university_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('experience', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('official_mail_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mobile_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('representative_both_details_member_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('representative_both_details_pkey'))
    )
    op.create_table('membership_counters',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('current_value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('membership_counters_pkey')),
    sa.UniqueConstraint('type', name=op.f('membership_counters_type_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('representative_autonomous_details',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('college_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('college_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('designation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('district', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pincode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('representative_autonomous_details_member_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('representative_autonomous_details_pkey'))
    )
    op.create_table('representative_university_details',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('college_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('university_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('college_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('designation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('district', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pincode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('representative_university_details_member_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('representative_university_details_pkey'))
    )
    # ### end Alembic commands ###
