"""add index to membership_id

Revision ID: f6ebb8ee750d
Revises: f1de37ff39df
Create Date: 2026-05-05 12:16:52.964543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6ebb8ee750d'
down_revision: Union[str, Sequence[str], None] = 'f1de37ff39df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_contact_messages_membership_id'), 'contact_messages', ['membership_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contact_messages_membership_id'), table_name='contact_messages')
    # ### end Alembic commands ###
